# Generated by Django 5.1.5 on 2025-02-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_aboutus_contacts_sitecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="mini_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Мини описание"
            ),
        ),
    ]
