# Generated by Django 5.1.5 on 2025-02-04 18:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
        migrations.RemoveField(
            model_name="publication",
            name="categories",
        ),
        migrations.AddField(
            model_name="page",
            name="categories",
            field=models.ManyToManyField(
                related_name="publications",
                to="myapp.publicationcategory",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Содержимое"),
        ),
    ]
