# Generated by Django 5.1.5 on 2025-02-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_morepage_options_morepageimage_pageimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="morepageimage",
            name="more_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_page",
                to="myapp.morepage",
            ),
        ),
    ]
