# Generated by Django 5.1.5 on 2025-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_morepageimage_more_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="morepage",
            options={"verbose_name": "ЦУР", "verbose_name_plural": "ЦУР"},
        ),
        migrations.AddField(
            model_name="morepage",
            name="mini_title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Цель"
            ),
        ),
    ]
