# Generated by Django 5.1.5 on 2025-03-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_morepage_options_morepage_mini_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="morepage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "ЦУР",
                "verbose_name_plural": "ЦУР",
            },
        ),
    ]
