# Generated by Django 5.1.5 on 2025-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_application_options_alter_morepage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageimage",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
