# Generated by Django 5.1.5 on 2025-04-15 21:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_pageimage_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=123, null=True)),
                ("image", models.FileField(upload_to="gallery")),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description3",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Третье Описание"
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="image4",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="images/",
                verbose_name="Четвертое изображение",
            ),
        ),
    ]
