# Generated by Django 5.1.5 on 2025-04-23 07:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_galleryimage_aboutus_description3_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description2_ky",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Второе Описание"
            ),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description2_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Второе Описание"
            ),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description3_ky",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Третье Описание"
            ),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description3_ru",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Третье Описание"
            ),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description_ky",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="document",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="document",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="title_ky",
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="title_ru",
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name="morepage",
            name="description_ky",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="morepage",
            name="description_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="morepage",
            name="mini_title_ky",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Цель"
            ),
        ),
        migrations.AddField(
            model_name="morepage",
            name="mini_title_ru",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Цель"
            ),
        ),
        migrations.AddField(
            model_name="morepage",
            name="title_ky",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="morepage",
            name="title_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ky",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Содержимое"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Содержимое"),
        ),
        migrations.AddField(
            model_name="news",
            name="mini_title_ky",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Мини описание"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="mini_title_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Мини описание"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_ky",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="description_ky",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="page",
            name="description_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_ky",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="title_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="pageimage",
            name="name_ky",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pageimage",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ky",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_ky",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="description_ky",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="publication",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="publication",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="publication",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="publicationcategory",
            name="name_ky",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="publicationcategory",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
