# Generated by Django 5.1.5 on 2025-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_alter_news_options_aboutus_description2_ky_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="title2_ky",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Второе Название"
            ),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="title2_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Второе Название"
            ),
        ),
    ]
