# Generated by Django 5.1.5 on 2025-05-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_aboutus_title2_ky_aboutus_title2_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageimage",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_page",
                to="myapp.page",
            ),
        ),
        migrations.CreateModel(
            name="FileCategoryPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_categories",
                        to="myapp.page",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pageimage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_category",
                to="myapp.filecategorypage",
            ),
        ),
    ]
