# Generated by Django 5.1.5 on 2025-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_pageimage_page_filecategorypage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecategorypage",
            name="title_ky",
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name="filecategorypage",
            name="title_ru",
            field=models.CharField(max_length=123, null=True),
        ),
    ]
