# Generated by Django 5.1.5 on 2025-06-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_filecategorypage_title_ky_filecategorypage_title_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="morepageimage",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "image"), ("file", "file")],
                default="image",
                max_length=123,
            ),
        ),
    ]
